services:

  backend:
    image: couchdb:3
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    healthcheck:
      test: curl -f http://localhost:5984/_up || exit 1
      start_period: 5s
      start_interval: 2s

  updated_samples:
    image: node:22-slim
    command: npx couchdb-bootstrap http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@backend:5984 samples
    volumes:
      - ./samples:/samples
    depends_on:
      backend:
        condition: service_healthy

  updated_code:
    image: node:22-slim
    command: npx couchdb-bootstrap http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@backend:5984 app
    volumes:
      - ./backend:/app
    depends_on:
      backend:
        condition: service_healthy

