services:

  backend:
    image: couchdb:3
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    healthcheck:
      test: curl -f http://localhost:5984/_up || exit 1
      interval: 2s
      timeout: 3s

  accessible_backend:
    image: curlimages/curl
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        alias put="curl -X PUT -u '${COUCHDB_USER}:${COUCHDB_PASSWORD}'"
        put backend:5984/hyperglosae
        put backend:5984/hyperglosae/_security --data '{"members":{"roles":[]},"admins":{"roles":["_admin"]}}'
        put backend:5984/_node/nonode@nohost/_config/couchdb/users_db_security_editable --data '"true"'
        put backend:5984/_users/_security --data '{"members":{"roles":[]},"admins":{"roles":["_admin"]}}'
    depends_on:
      backend:
        condition: service_healthy

  sample_users:
    image: curlimages/curl
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        alias put="curl -X PUT -u '${COUCHDB_USER}:${COUCHDB_PASSWORD}'"
        put backend:5984/_users
        put backend:5984/_users/org.couchdb.user:alice --data '{"name":"alice", "password":"whiterabbit", "roles":[], "type":"user"}'
        put backend:5984/_users/org.couchdb.user:bill --data '{"name":"bill", "password":"madhatter", "roles":[], "type":"user"}'
        put backend:5984/_users/org.couchdb.user:christophe --data '{"name":"christophe", "password":"redqueen", "roles":[], "type":"user"}'
    depends_on:
      backend:
        condition: service_healthy

  updated_samples:
    image: node:22-slim
    command: npx couchdb-bootstrap http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@backend:5984 samples
    volumes:
      - ./samples:/samples
    depends_on:
      backend:
        condition: service_healthy

  updated_code:
    image: node:22-slim
    command: npx couchdb-push http://${COUCHDB_USER}:${COUCHDB_PASSWORD}@backend:5984/hyperglosae app
    volumes:
      - ./backend/src:/app
    depends_on:
      backend:
        condition: service_healthy

