services:

  backend:
    extends:
      file: docker-compose.test.yml
      service: backend
    environment:
      - COUCHDB_USER
      - COUCHDB_PASSWORD
    volumes:
      - ./data:/opt/couch/data

  accessible_backend:
    extends:
      file: docker-compose.test.yml
      service: accessible_backend
    depends_on:
      backend:
        condition: service_healthy

  updated_code:
    extends:
      file: docker-compose.test.yml
      service: updated_code
    depends_on:
      backend:
        condition: service_healthy
  
  frontend:
    image: benel/hyperglosae

  proxy:
    extends:
      file: docker-compose.test.yml
      service: proxy
    depends_on:
      - backend
      - frontend

