services:

  backend:
    extends:
      file: docker-compose.dev.yml
      service: backend

  accessible_backend:
    extends:
      file: docker-compose.dev.yml
      service: accessible_backend
    depends_on:
      backend:
        condition: service_healthy

  sample_users:
    extends:
      file: docker-compose.dev.yml
      service: sample_users
    depends_on:
      backend:
        condition: service_healthy

  updated_samples:
    extends:
      file: docker-compose.dev.yml
      service: updated_samples
    depends_on:
      backend:
        condition: service_healthy
    restart: on-failure

  updated_code:
    extends:
      file: docker-compose.dev.yml
      service: updated_code
    depends_on:
      backend:
        condition: service_healthy
    restart: on-failure

  frontend:
    image: nginx
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./settings/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  proxy:
    image: haproxy
    ports:
      - 80:80
    volumes:
      - ./settings:/usr/local/etc/haproxy:ro
    depends_on:
      - backend
      - frontend

