projectName: Hyperglosae
baseURL: http://localhost
scenarios:
  - name: Bookshelf
    path: ./impact_of_bookshelf.js
  - name: Parallel texts
    path: ./impact_of_parallel_texts.js
containers:
  - hyperglosae-proxy-1
databaseContainers:
  - hyperglosae-frontend-1 # Local network
  - hyperglosae-backend-1

