projectName: Hyperglosae
baseURL: http://localhost
scenarios:
  - name: Public browsing
    path: ./scenario.js
containers:
  - hyperglosae-proxy-1
databaseContainers:
  - hyperglosae-frontend-1 # Local network
  - hyperglosae-backend-1

