name: Expose tests
on: 
  workflow_call

jobs:
      
    ExposeTest:
        runs-on: ubuntu-latest
        steps:
            - name: Download sources
              uses: actions/checkout@v3
              with:
                repository: ${{ github.event.pull_request.head.repo.full_name }}
                ref: htmlPreview
            - name: Get green it report zip
              uses: actions/download-artifact@v3
              with:
                name: green-it-report
                path: /home/runner/work/output
            - name: Copy artifact into repo
              run: cp -r /home/runner/work/output/ /home/runner/work/HyperGlosae/HyperGlosae/ 
            - name: Commit artifact on htmlPreview branch
              uses: EndBug/add-and-commit@v9
              with:
                add: "*"
                default_author: github_actions
                message: "PROCESS : Commit Green IT Analysis HTML file output to be previewed"
                push: origin htmlPreview
            - name: Create link to go to html file preview
              run:
                echo "https://htmlpreview.github.io/?https://github.com/vallhallalm/HyperGlosae/htmlPreview/output/global.html"
        
    