name: Publish

on:
  push:
    branches:
      - 'main'

jobs:

  test:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download sources
        uses: actions/checkout@v4
      - name: Get frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: benel
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: . #No checkout
          push: true
          tags: benel/hyperglosae:latest
